app/urls.py
from django.contrib import admin
from django.urls import path
from .views import index , AllPostsView,about_site,PostDetailView,mit


app_name = 'app'
urlpatterns = [
    path('', index,name="index"),
    path('mit/', mit,name="mit"),
    path('about_site/', about_site,name="about_site"),
    path('posts/', AllPostsView.as_view(),name="posts"),
    path('posts/<str:slug>', PostDetailView.as_view(), name='post_detail'),
    #path('create/', creat_post,name="craete_post"),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path,include,re_path
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('app.urls')),
    re_path(r'^ckeditor/', include('ckeditor_uploader.urls')),
]
urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/models.py
from django.db import models
import uuid
# Create your models here.

from django.db import models
from django.urls import reverse
from django.utils.text import slugify
from django.contrib.auth.models import User

class Category(models.Model):
    name = models.CharField(max_length=255, unique=True)
    slug = models.SlugField(editable=False)

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Category, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('app:posts_by_category', args=[self.slug])
        
from ckeditor_uploader.fields import RichTextUploadingField 
class Post(models.Model):
    title = models.CharField(max_length=255)
    slug = models.SlugField(unique=True, editable=False)
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='blog_posts')
    content = RichTextUploadingField()
    created_on = models.DateTimeField(auto_now_add=True)
    categories = models.ManyToManyField(Category, related_name='blog_posts')

    class Meta:
        ordering = ['-created_on']

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        uid = str(uuid.uuid4())[:8]
        self.slug = uid+slugify(self.title)
        super(Post, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('app:post_detail', args=[self.slug])

app/forms.py
from django import forms
from .models import Category


class PostForm(forms.Form):
    title = forms.CharField(max_length=255)
    category = forms.ModelChoiceField(queryset=Category.objects.all(), empty_label=None)
    content = forms.CharField(widget=forms.Textarea(attrs={'id': 'post_content'}))

app/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse

from django.views.generic import ListView,DetailView
from django.core.paginator import Paginator
from .models import Post
from .forms import PostForm


# Create your views here.
def index(request):
    return render(request,'app/index.html')

def mit(request):
    return render(request,'app/license.html')    

def creat_post(request):
    if request.method == 'GET':
        form = PostForm()
        return render(request,'app/create_post.html',{'form':form}) 
    if request.method == 'POST': 
        form = PostForm(request.POST) 
        if form.is_valid():
            form.save()
            return  redirect('app/posts')

def about_site(request):
    return render(request,'app/about_site.html')


from django.db.models import Q
class AllPostsView(ListView):
    model = Post
    template_name = 'app/list_posts.html'
    context_object_name = 'posts'
    paginate_by = 4

    def get_queryset(self):
        queryset = super().get_queryset()
        category = self.request.GET.get('category')

        search_term = self.request.GET.get('search', None)
        if search_term:
            queryset = queryset.filter(
                Q(title__icontains=search_term) | Q(content__icontains=search_term)
            )

        if category:
            queryset = queryset = queryset.filter(categories__pk=category)

        return queryset


    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['search_term'] = self.request.GET.get('search')
        return context



class PostDetailView(DetailView):
    model = Post
    template_name = "app/post_detail.html"        

templates/app/about_site.html
{% extends 'app/base.html'%}

{% block title %}
About TechTalk
{% endblock title%}

{% block content %}

<section class="jumbotron text-center m-3 p-3 ">
    <div class="container">
      <h1 class="jumbotron-heading">TechTalk</h1>
      <p class="lead text-muted">
        Welcome to my personal blog where I share my insights, experiences, and opinions about all things related to information technology (IT) and programming.

        As a passionate programmer and tech enthusiast, I believe that the world of IT is constantly evolving, and there's always something new to learn and explore. Through this blog, I aim to provide valuable insights and tips on various programming languages, tools, and frameworks that I have used or come across in my career.
        
        Whether you are a beginner in the field of programming or an experienced developer, this blog has something for everyone. From coding best practices to software development methodologies, I will cover a range of topics that will help you enhance your skills and keep up with the latest trends in the industry.
        
        In addition to sharing my knowledge, I also welcome feedback and suggestions from my readers. So, feel free to leave comments or get in touch with me if you have any questions or ideas for future blog posts.
        
        Thank you for visiting my blog, and I hope you find the information here useful and informative.
        
      </p>
        
      
    </div>
  </section>
{% endblock content %}

templates/app/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}TechTalk{% endblock title %}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootswatch@5.2.3/dist/lux/bootstrap.min.css">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js" integrity="sha384-cuYeSxntonz0PPNlHhBs68uyIAVpIIOZZ5JqeqvYYIcEL727kskC66kF92t6Xl2V" crossorigin="anonymous"></script>
    <script src="https://cdn.ckeditor.com/ckeditor5/36.0.1/classic/ckeditor.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.3/jquery.min.js" integrity="sha512-STof4xm1wgkfm7heWqFJVn58Hm3EtS31XFaagaa8VMReCXAkQnJZ+jEy8PCC/iT18dFy95WcExNHFTqLyp72eQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
     {% block style %}

     <style>
     .scrollable-list {
      overflow-x: scroll;
      white-space: nowrap;
      -webkit-overflow-scrolling: touch; /* For iOS devices */
    }
    .scrollable-list ul {
      list-style: none;
      padding: 0;
      margin: 0;
    }
    .scrollable-list li {
      display: inline-block;
      padding: 10px;
      margin-right: 5px;
      background-color: #f2f2f2;
    }
    .controls {
      margin-top: 10px;
      text-align: center;
    }
  </style>
     {% endblock style %}
</head>
<body>
  <nav class="navbar navbar-expand-lg border shadow-sm ">
    <div class="container">
      <a class="navbar-brand" href="{% url 'app:posts' %}">TechTalk</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarColor01">
        <ul class="navbar-nav me-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'app:posts' %}">Articles</a>
          </li>
          
         
        </ul>
      </div>
    </div>
  </nav>

  <div class="container">
    <form class="m-2" method="get" action="{% url 'app:posts' %}">
      <div class="input-group mb-3">
        <input type="text" name="search"  class="form-control" placeholder="... " aria-label="" aria-describedby="button-addon2">
        <input class="btn btn-primary" value="SEARCH" type="submit" />
      </div>
    </form>
  
    <div class="row">
      <div class="col">
        {% block content %}
 
        {% endblock content %}

      </div>
      <div style="border-left: 1px solid rgb(204, 203, 203);" class="col-md-3 ">
        <h4>Categories</h4>
         
          {% for category in categories %}
            
              
                <a href="/posts?category={{category.id}}">{{ category.name }}</a><br>
              
            
          {% endfor %}
     
      <div>
        <hr>
        
        <a href="{% url 'app:mit' %}">MIT License</a>
<br>
        <a  href="{% url 'app:about_site' %}" >About</a>

       <hr>
      <p>Crated with ❤️ and Django by Taha Elkarroumy</p> 
      </div>
      
      </div>
    </div>
  </div>
  



</body>
</html>

templates/app/category_list.html
    <h1>All Categories</h1>
    <ul>
        {% for category in categories %}
            <li><a href="{% url 'post-list-by-category' category.pk %}">{{ category.name }}</a></li>
        {% endfor %}
    </ul>

templates/app/create_post.html
{% extends 'app/base.html' %}

{% block content %}
  <h1>Create a new post</h1>
  <form action="/" method="post">
    {% csrf_token %}
    {{ form }}
    <button id="btn_submit" type="submit">Create post</button>
  </form>

 
{% endblock %}

templates/app/index.html
{% extends 'app/base.html'%}

{% block title %}
TechTalk
{% endblock title%}

{% block content %}

<h1>Taha Elkarroumy</h1>
<p>
    As a Python web developer, I specialize in developing web applications using Python-based web frameworks such as Django and Flask. I am well-versed in programming concepts and design patterns and can develop efficient, scalable, and robust web applications that meet clients' requirements.


I am familiar with various database management systems such as MySQL, PostgreSQL, and MongoDB and can design and implement database schemas and queries to ensure data consistency, integrity, and security.


In addition to technical skills, I possess excellent communication skills and can work closely with clients to understand their requirements and provide technical solutions that meet their needs. I am also a fast learner, adaptable, and stay up-to-date with the latest industry trends and technologies to ensure that my skills are relevant and competitive.
</p>

{% endblock content %}

templates/app/license.html
{% extends 'app/base.html' %}

{% block content %}
<h1>LICENSE</h1> 
<p class="card p-3">
    MIT License

Copyright (c) 2023 Taha Elkarroumy

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
</p>
 
{% endblock %}

templates/app/list_posts.html
{% extends 'app/base.html' %}

{% load humanize %}
{% block content %}

{% if not posts %}
<center><h1>No Posts yet </h1></center>
{% endif %}

{% if search_term %}
<center><h1>Results for : {{search_term}} </h1></center>
{% endif %}

 
<div class="container">
  <div class="row flex-row">
    {% for post in posts %}
    <div class="col">
      <div class="card h-100">
        <div class="card-body">
          <h2><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h2>
          <p class="meta">Posted  {{ post.created_on|naturaltime }}.  by {{ post.author }}</p>
           <a href="{{ post.get_absolute_url }}" class="btn btn-primary">Read More</a>

        </div>
      </div>
    </div>
   
    {% endfor %}
  </div>
</div>


  {% if is_paginated %}
    <nav aria-label="Posts pagination">
      <ul class="pagination justify-content-center">
        {% if page_obj.has_previous %}
          <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">Previous</a></li>
        {% else %}
          <li class="page-item disabled"><span class="page-link">Previous</span></li>
        {% endif %}

        {% for page in paginator.page_range %}
          {% if page == page_obj.number %}
            <li class="page-item active"><span class="page-link">{{ page }} <span class="sr-only">(current)</span></span></li>
          {% else %}
            <li class="page-item"><a class="page-link" href="?page={{ page }}">{{ page }}</a></li>
          {% endif %}
        {% endfor %}

        {% if page_obj.has_next %}
          <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a></li>
        {% else %}
          <li class="page-item disabled"><span class="page-link">Next</span></li>
        {% endif %}
      </ul>
    </nav>
  {% endif %}
{% endblock %}

templates/app/post_detail.html
{% extends 'app/base.html' %}

{% load humanize %}
{% block content %}
<div class="container">

    <h1>{{ object.title }}</h1>
    <p class="meta">Posted {{ post.created_on|naturaltime }}.  by {{ post.author }}</p>
    <hr>
    <p>{{ object.content| safe }}</p>
</div>
    
{% endblock %}